package com.helper.util;

/**
 * @author Created by Amit on 5/8/2018.
 */

public interface CategoryType {

    int CATEGORY_TYPE_UNKNOWN = -1;
    int CATEGORY_TYPE_DEFAULT = 0;
    int SLIDER_PACKAGE = 1;
    int SLIDER_SUBSCRIPTION_PLAN_ALL = 2;
    int SLIDER_SUBSCRIPTION_PLAN_SINGLE = 3;
    int SLIDER_EXAM_PAGE = 4;
    int SLIDER_PLAY_STORE = 5;
    int SLIDER_WEB_URL = 6;
    int CATEGORY_TYPE_MOCK = 7;
    int CATEGORY_TYPE_ARTICLE = 8;
    int CATEGORY_TYPE_MOCK_ARTICLE = 9;
    int CATEGORY_TYPE_PDF = 10;
    int CATEGORY_TYPE_MOCK_ARTICLE_PDF = 11;
    int CATEGORY_TYPE_CALENDER = 12;
    int CATEGORY_TYPE_NCERT_CLASS = 13;
    int CATEGORY_TYPE_NEWS = 14;
    int CATEGORY_TYPE_CATEGORY_GRID = 15;
    int CATEGORY_TYPE_MOCK_ARTICLE_ONLY = 16;
    int CATEGORY_TYPE_CATEGORY_LIST = 17;
    int CATEGORY_TYPE_SUB_CATEGORY = 21;
    int CATEGORY_TYPE_PAID = 31;
    int CATEGORY_TYPE_TOOL_DICTIONARY = 32;
    int CATEGORY_TYPE_TOOL_TRANSLATOR = 33;
    int CATEGORY_TYPE_TOOL_SPELL_CHECKER = 34;
    int CATEGORY_TYPE_TOOL_PRONUNCIATION = 35;
    int CATEGORY_TYPE_WORD_POWER = 36;
    int CATEGORY_TYPE_QUOTES = 37;
    int CATEGORY_TYPE_PDF_BOOKS_LIST = 38;

    int LATEST_BOOKS = 1001;
    int CATEGORY_TYPE_NOTES_PRACTICE_TEST = 1002;
    int CATEGORY_TYPE_NOTES_PRACTICE_OTHER_TEST = 1003;
    int CATEGORY_TYPE_NOTES_SUBJECT = 1004;
    int CATEGORY_TYPE_SUBJECT = 1005;
    int CATEGORY_TYPE_PRACTICE_TEST = 1006;
    int CATEGORY_TYPE_MOCK_WITH_SUBCATS = 1007;
    int CATEGORY_TYPE_BOOK_PDF = 1008;
    int CATEGORY_TYPE_MOCK_WITH_HEADER = 1009;
    int CATEGORY_TYPE_ARTICLE_WITH_HEADER = 1010;

    int CATEGORY_TYPE_ARTICLE_ADVANCE_EDITORIAL = 1011;
    int CATEGORY_TYPE_ARTICLE_ADVANCE_EDITORIAL_SUB_CAT = 1012;
    int CATEGORY_TYPE_ARTICLE_ADVANCE_EDITORIAL_WEBVIEW = 1013;
    int CATEGORY_TYPE_ARTICLE_ADVANCE_EDITORIAL_SUB_CAT_WEBVIEW = 1014;

    int CATEGORY_TYPE_PREVIOUS_YEAR_PAPER_JEE = 1016;
    int CATEGORY_TYPE_CLASSES_NCERT = 1017;
    int CATEGORY_TYPE_DPP = 1015;

    int WB_CONTENT_TYPE_RESULT = 1021; //open Content through  Board Selector
    int WB_CONTENT_TYPE_DATE_SHEET = 1022; //open Content through  Board Selector
    int WB_RESULT_PERSONAL = 1023;  //open Content Direct
    int WB_TIMETABLE_PERSONAL = 1024; //open Content Direct

    int WB_STUDY_BOARD_CLASS = 1025; // Study type1
    int WB_STUDY_GOVT_JOB = 1026; // Study type2
    int WB_STUDY_NEET_JEE = 1027; // Study type3
    int WB_STUDY_DAILY_BOOSTER = 1028; //1
    int WB_STUDY_TOP_EXAM = 1029; //2
    int WB_STUDY_EXAM_MASTER = 1030; //3
    int WB_STUDY_COURSES_BOOKS = 1031; //4
    int WB_STUDY_VIDEO_OTHERS = 1032;
    int WB_STUDY_BOOKS_ADVACE_FREE_BOOK = 1033;
    int WB_STUDY_MCQ_ADVACE_PAID = 1034;

    int CATEGORY_TYPE_CATEGORY_TABS = 1035;
    int TYPE_PRE_YEAR_PAPER = 1036;
    int TYPE_IMPORTANT_INFO = 1037;
    int CATEGORY_TYPE_SPEED_TEST = 1038;
}
